- name: Homework 4 - creating a empty file /etc/iaac with rigths 0500
  hosts: iaas
  gather_facts: yes

  roles:
        - empty-file-0500

- name: fetch a linux distro name/version
  hosts: all
  gather_facts: yes

  roles:
        - distr-name-and-version

