---
# tasks file for distr-name-and-version

  - name: Print dist name and version
    debug:
        msg:
         - "{{ansible_distribution}} {{ansible_distribution_version}}"
    register: dist_info

  - name: Printing hostnames together with distro name/version
    debug:
        msg:
        - "{{ansible_hostname}}: {{dist_info.msg}}"
